version: "2.1"

volumes:
  downloads: {}
  duplicati: {}
  duplicati-tailscale: {}
  jellyfin: {}
  jellyfin-tailscale: {}
  letsencrypt: {}
  netdatalib: {}
  netdatacache: {}
  nzbhydra: {}
  nzbhydra-tailscale: {}
  ombi: {}
  ombi-tailscale: {}
  overseerr: {}
  overseerr-tailscale: {}
  plex: {}
  plex-tailscale: {}
  prowlarr: {}
  prowlarr-tailscale: {}
  proxy: {}
  radarr: {}
  radarr-tailscale: {}
  sabnzbd: {}
  sabnzbd-tailscale: {}
  sonarr: {}
  sonarr-tailscale: {}
  syncthing: {}
  syncthing-tailscale: {}
  tautulli: {}
  tautulli-tailscale: {}

services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    image: linuxserver/plex:1.32.6@sha256:5405786ccc12107d9277ff0cf2a939fe03e4c41b65f50ea2c5f1a163b50bcdf4
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-plex
      TAILSCALE_SERVE_PORT: 32400
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 32400:32400/tcp
    tmpfs:
      - /tmp
    volumes:
      - plex:/config
      - downloads:/downloads
      - plex-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-jellyfin
  jellyfin:
    image: linuxserver/jellyfin:10.8.11@sha256:0cbf45c0540d0eefdbf496c7226fe6d3ded0fd720f1c3ca4ed1a0c913b28db7e
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-jellyfin
      TAILSCALE_SERVE_PORT: 8096
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    tmpfs:
      - /tmp
    volumes:
      - jellyfin:/config
      - downloads:/downloads
      - jellyfin-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:3.0.10@sha256:3e25bfa2304448e26d43bf09e6291b238c43db897764846b084f2f3f1176c40f
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-sonarr
      TAILSCALE_SERVE_PORT: 8989
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:8989:8989/tcp
    tmpfs:
      - /tmp
    volumes:
      - sonarr:/config
      - downloads:/downloads
      - sonarr-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    image: linuxserver/radarr:5.0.3@sha256:e660626b6f7e08298573dba7e89b0d40d1b11dceb9010a28074385567ad36fe7
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-radarr
      TAILSCALE_SERVE_PORT: 7878
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:7878:7878/tcp
    tmpfs:
      - /tmp
    volumes:
      - radarr:/config
      - downloads:/downloads
      - radarr-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-prowlarr
  prowlarr:
    image: linuxserver/prowlarr:1.10.0-develop@sha256:656f375d3a36fe895ac354bf8e69a0ddc5bb52ce4cc71f0e0efa3d2d4270b479
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-prowlarr
      TAILSCALE_SERVE_PORT: 9696
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:9696:9696/tcp
    tmpfs:
      - /tmp
    volumes:
      - prowlarr:/config
      - downloads:/downloads
      - prowlarr-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-nzbhydra
  nzbhydra:
    image: linuxserver/nzbhydra2:5.1.11@sha256:12968e97d00ba5f59904425e27ec5601b17f76c9057e8e0a66e8ff0edd281deb
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-nzbhydra
      TAILSCALE_SERVE_PORT: 5076
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:5076:5076/tcp
    tmpfs:
      - /tmp
    volumes:
      - nzbhydra:/config
      - downloads:/downloads
      - nzbhydra-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-ombi
  ombi:
    image: linuxserver/ombi:4.43.5@sha256:092c21fb93a9ffa4474bbe4cb4d369742f7cc0d77297adbf2c41a3226cb07aab
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-ombi
      TAILSCALE_SERVE_PORT: 3579
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:3579:3579/tcp
    tmpfs:
      - /tmp
    volumes:
      - ombi:/config
      - ombi-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-overseerr
  overseerr:
    image: lscr.io/linuxserver/overseerr:1.33.2@sha256:afa85c37a725844a073e16ba870c6124943a9e8b05ed6791a1803e29c21f45a3
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-overseerr
      TAILSCALE_SERVE_PORT: 5055
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:5055:5055/tcp
    tmpfs:
      - /tmp
    volumes:
      - overseerr:/config
      - overseerr-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-sabnzbd
  sabnzbd:
    image: linuxserver/sabnzbd:4.1.0@sha256:c2ef513dfd4d23fc19cf529029e7ee293ac4980e41fd132a87adecfb2a12f920
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-sabnzbd
      TAILSCALE_SERVE_PORT: 8080
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:8080:8080/tcp
    tmpfs:
      - /tmp
    volumes:
      - sabnzbd:/config
      - downloads:/downloads
      - sabnzbd-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-tautulli
  tautulli:
    image: linuxserver/tautulli:2.13.2@sha256:2cbf31dc542f4fc4b70e62a0970215eed0efb8f154ceba830fbc3e676bc32615
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-tautulli
      TAILSCALE_SERVE_PORT: 8181
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:8181:8181/tcp
    tmpfs:
      - /tmp
    volumes:
      - tautulli:/config
      - sabnzbd-tailscale:/var/lib/tailscale

    # https://hub.docker.com/r/netdata/netdata
  netdata:
    image: netdata/netdata:v1.43.1@sha256:a919c4c2d0391d6e42658134f980878b4b1e0ed9f9454c5d199240bbe5d9d7ce
    privileged: true
    cap_add:
      - SYS_PTRACE
    environment:
      DOCKER_HOST: "/var/run/balena.sock"
      PGID: "990" # ls -nd /var/run/balena.sock | awk '{print $4}'
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.sysfs: 1
    ports:
      - 127.0.0.1:19999:19999/tcp
    security_opt:
      - apparmor:unconfined
    tmpfs:
      - /tmp
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata

  # https://docs.linuxserver.io/images/docker-duplicati
  duplicati:
    image: lscr.io/linuxserver/duplicati:v2.0.6.3-2.0.6.3_beta_2021-06-17-ls160@sha256:9cf7c7a14bf1474d44aa29d329552bf32af58090f4cfa5e61e35a88b2cd4677e
    restart: unless-stopped
    environment:
      PUID: "0"
      PGID: "0"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-duplicati
      TAILSCALE_SERVE_PORT: 8200
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:8200:8200/tcp
    tmpfs:
      - /tmp
    volumes:
      - duplicati:/config
      - duplicati-tailscale:/var/lib/tailscale
      # any volumes that might be worth backing up
      - syncthing:/volumes/syncthing
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - ombi:/volumes/ombi
      - overseerr:/volumes/overseerr
      - sabnzbd:/volumes/sabnzbd
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - tautulli:/volumes/tautulli

  # https://docs.linuxserver.io/images/docker-syncthing
  syncthing:
    image: lscr.io/linuxserver/syncthing:1.25.0@sha256:37610128d1fe84a78e541db19123dafe1be3c2d081cc78d4afa14ab151d7d5ac
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-syncthing
      TAILSCALE_SERVE_PORT: 8384
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:8384:8384/tcp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    tmpfs:
      - /tmp
    volumes:
      - syncthing:/config
      - syncthing-tailscale:/var/lib/tailscale
      # any volumes that might be worth syncronizing between machines
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - ombi:/volumes/ombi
      - overseerr:/volumes/overseerr
      - sabnzbd:/volumes/sabnzbd
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - tautulli:/volumes/tautulli

  # https://hub.docker.com/r/jc21/nginx-proxy-manager
  proxy:
    image: jc21/nginx-proxy-manager:2.10.4@sha256:e1000dd653d193ac70cb3635c27333b0183a11f987e2b1c6043589d9d948bc0f
    ports:
      - 80:80/tcp
      - 127.0.0.1:81:81/tcp
      - 443:443/tcp
    tmpfs:
      - /tmp
    volumes:
      - proxy:/data
      - letsencrypt:/etc/letsencrypt
