version: "2.1"

volumes:
  downloads: {}
  duplicati: {}
  duplicati-tailscale: {}
  jellyfin: {}
  jellyfin-tailscale: {}
  letsencrypt: {}
  netdatalib: {}
  netdatacache: {}
  nzbhydra: {}
  nzbhydra-tailscale: {}
  ombi: {}
  ombi-tailscale: {}
  overseerr: {}
  overseerr-tailscale: {}
  plex: {}
  plex-tailscale: {}
  prowlarr: {}
  prowlarr-tailscale: {}
  proxy: {}
  radarr: {}
  radarr-tailscale: {}
  sabnzbd: {}
  sabnzbd-tailscale: {}
  sonarr: {}
  sonarr-tailscale: {}
  syncthing: {}
  syncthing-tailscale: {}
  tautulli: {}
  tautulli-tailscale: {}

services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    image: linuxserver/plex:1.32.7@sha256:fedd6ee2ba80c509e6433a23d3dcbbade12bda0162c879bc1a64d7c75a2810fc
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-plex
      TAILSCALE_SERVE_PORT: 32400
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 32400:32400/tcp
    tmpfs:
      - /tmp
    volumes:
      - plex:/config
      - downloads:/downloads
      - plex-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-jellyfin
  jellyfin:
    image: linuxserver/jellyfin:10.8.12@sha256:78a082856d20ee1c0477b935d234d3ee61dbc516c6ff90f63688aab0480ea7d4
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-jellyfin
      TAILSCALE_SERVE_PORT: 8096
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    tmpfs:
      - /tmp
    volumes:
      - jellyfin:/config
      - downloads:/downloads
      - jellyfin-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:3.0.10@sha256:cb695458b280551a4b2e8b925c4deba1772dabe82cd15a2c684ff36bca7fa9f8
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-sonarr
      TAILSCALE_SERVE_PORT: 8989
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:8989:8989/tcp
    tmpfs:
      - /tmp
    volumes:
      - sonarr:/config
      - downloads:/downloads
      - sonarr-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    image: linuxserver/radarr:5.1.3@sha256:ee96728ead2d3e6d7ccd32a96e16c13ea3818ffa7579fb0c11fe205f9733ae74
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-radarr
      TAILSCALE_SERVE_PORT: 7878
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:7878:7878/tcp
    tmpfs:
      - /tmp
    volumes:
      - radarr:/config
      - downloads:/downloads
      - radarr-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-prowlarr
  prowlarr:
    image: linuxserver/prowlarr:1.10.2-develop@sha256:e9acf1539da047e2163aed585ee627ca91cdd34810b178235df3265829e4c6b2
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-prowlarr
      TAILSCALE_SERVE_PORT: 9696
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:9696:9696/tcp
    tmpfs:
      - /tmp
    volumes:
      - prowlarr:/config
      - downloads:/downloads
      - prowlarr-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-nzbhydra
  nzbhydra:
    image: linuxserver/nzbhydra2:5.1.11@sha256:3aa16d4279230eb131c9e895563b84895020edc132aee72e3ffc2cbdcd05a602
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-nzbhydra
      TAILSCALE_SERVE_PORT: 5076
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:5076:5076/tcp
    tmpfs:
      - /tmp
    volumes:
      - nzbhydra:/config
      - downloads:/downloads
      - nzbhydra-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-ombi
  ombi:
    image: linuxserver/ombi:4.43.5@sha256:487164e49ef5673c1c869b14f82fbde1dfb5f76f04699d547f9b4e901b9bfab8
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-ombi
      TAILSCALE_SERVE_PORT: 3579
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:3579:3579/tcp
    tmpfs:
      - /tmp
    volumes:
      - ombi:/config
      - ombi-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-overseerr
  overseerr:
    image: lscr.io/linuxserver/overseerr:1.33.2@sha256:b4ec9fc82cb5c46e8daf293ecd40efc691bdda28d803f1138cf73334a0e413d7
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-overseerr
      TAILSCALE_SERVE_PORT: 5055
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:5055:5055/tcp
    tmpfs:
      - /tmp
    volumes:
      - overseerr:/config
      - overseerr-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-sabnzbd
  sabnzbd:
    image: linuxserver/sabnzbd:4.1.0@sha256:d43f9f1fac38b3b6b1bbd45855141a78a6e2758bc56dacf22d07858a0cc1f382
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-sabnzbd
      TAILSCALE_SERVE_PORT: 8080
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:8080:8080/tcp
    tmpfs:
      - /tmp
    volumes:
      - sabnzbd:/config
      - downloads:/downloads
      - sabnzbd-tailscale:/var/lib/tailscale

  # https://docs.linuxserver.io/images/docker-tautulli
  tautulli:
    image: linuxserver/tautulli:2.13.2@sha256:6195b187030637f5588c33988b3686b96f003c726b22958ee0d589549c6fb50f
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-tautulli
      TAILSCALE_SERVE_PORT: 8181
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:8181:8181/tcp
    tmpfs:
      - /tmp
    volumes:
      - tautulli:/config
      - sabnzbd-tailscale:/var/lib/tailscale

    # https://hub.docker.com/r/netdata/netdata
  netdata:
    image: netdata/netdata:v1.43.2@sha256:0116a5a4dbfedd84d80eba320f5d99d547da5d9bc0841adde0d7f13bed25f73a
    privileged: true
    cap_add:
      - SYS_PTRACE
    environment:
      DOCKER_HOST: "/var/run/balena.sock"
      PGID: "990" # ls -nd /var/run/balena.sock | awk '{print $4}'
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.sysfs: 1
    ports:
      - 127.0.0.1:19999:19999/tcp
    security_opt:
      - apparmor:unconfined
    tmpfs:
      - /tmp
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata

  # https://docs.linuxserver.io/images/docker-duplicati
  duplicati:
    image: lscr.io/linuxserver/duplicati:v2.0.6.3-2.0.6.3_beta_2021-06-17-ls160@sha256:9cf7c7a14bf1474d44aa29d329552bf32af58090f4cfa5e61e35a88b2cd4677e
    restart: unless-stopped
    environment:
      PUID: "0"
      PGID: "0"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-duplicati
      TAILSCALE_SERVE_PORT: 8200
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:8200:8200/tcp
    tmpfs:
      - /tmp
    volumes:
      - duplicati:/config
      - duplicati-tailscale:/var/lib/tailscale
      # any volumes that might be worth backing up
      - syncthing:/volumes/syncthing
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - ombi:/volumes/ombi
      - overseerr:/volumes/overseerr
      - sabnzbd:/volumes/sabnzbd
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - tautulli:/volumes/tautulli

  # https://docs.linuxserver.io/images/docker-syncthing
  syncthing:
    image: lscr.io/linuxserver/syncthing:1.26.1@sha256:e5bec869c5903d9567d1de1c6c7e612264ef3b5a79f5a31cb4b741fdf65e691a
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest|ghcr.io/tailscale-dev/docker-mod:main"
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: mediaserver-syncthing
      TAILSCALE_SERVE_PORT: 8384
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:8384:8384/tcp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    tmpfs:
      - /tmp
    volumes:
      - syncthing:/config
      - syncthing-tailscale:/var/lib/tailscale
      # any volumes that might be worth syncronizing between machines
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - ombi:/volumes/ombi
      - overseerr:/volumes/overseerr
      - sabnzbd:/volumes/sabnzbd
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - tautulli:/volumes/tautulli

  # https://hub.docker.com/r/jc21/nginx-proxy-manager
  proxy:
    image: jc21/nginx-proxy-manager:2.10.4@sha256:e1000dd653d193ac70cb3635c27333b0183a11f987e2b1c6043589d9d948bc0f
    ports:
      - 80:80/tcp
      - 127.0.0.1:81:81/tcp
      - 443:443/tcp
    tmpfs:
      - /tmp
    volumes:
      - proxy:/data
      - letsencrypt:/etc/letsencrypt
