version: "2.1"

volumes:
  downloads: {}
  duplicati: {}
  jellyfin: {}
  letsencrypt: {}
  netdatalib: {}
  netdatacache: {}
  nzbhydra: {}
  ombi: {}
  overseerr: {}
  plex: {}
  prowlarr: {}
  proxy: {}
  radarr: {}
  sabnzbd: {}
  sonarr: {}
  syncthing: {}
  tailscale: {}
  tautulli: {}

services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    image: linuxserver/plex:1.32.5@sha256:10a314af4af2b015c13019679698670253a9a920b9e56c4e8ef3c0ac057ea567
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest"
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 32400:32400/tcp
    tmpfs:
      - /tmp
    volumes:
      - plex:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-jellyfin
  jellyfin:
    image: linuxserver/jellyfin:10.8.10@sha256:a1f932e56b0760b9dfe5377b9e8860c7f36aa36246d732d32b3924aa712b0230
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest"
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    tmpfs:
      - /tmp
    volumes:
      - jellyfin:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:3.0.10@sha256:995c2517286012bcb1c9a26eb96877ff02c7ef4b47278a26d16df677898de63b
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest"
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:8989:8989/tcp
    tmpfs:
      - /tmp
    volumes:
      - sonarr:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    image: linuxserver/radarr:4.7.5@sha256:88b781066210e82aae174badeb9d84fd134d50a1cb50c0fdc4cacb69402d0750
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest"
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:7878:7878/tcp
    tmpfs:
      - /tmp
    volumes:
      - radarr:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-prowlarr
  prowlarr:
    image: linuxserver/prowlarr:1.8.5-develop@sha256:70bd038143d05569fe339fcbe1b22c3760bf6bac23d5d69c8a7d98857e051a28
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest"
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:9696:9696/tcp
    tmpfs:
      - /tmp
    volumes:
      - prowlarr:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-nzbhydra
  nzbhydra:
    image: linuxserver/nzbhydra2:5.1.10@sha256:f0145e2caf06c590c60289331d6924d7b02b42ca9c3449a7bc17f68a84708176
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest"
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:5076:5076/tcp
    tmpfs:
      - /tmp
    volumes:
      - nzbhydra:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-ombi
  ombi:
    image: linuxserver/ombi:4.43.5@sha256:57e31d9af0443361135e61cdc320a964946dbf18b84485291b9328717a2dccf1
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest"
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:3579:3579/tcp
    tmpfs:
      - /tmp
    volumes:
      - ombi:/config

  # https://docs.linuxserver.io/images/docker-overseerr
  overseerr:
    image: lscr.io/linuxserver/overseerr:1.33.2@sha256:b5e038c47d598de471ff769884cb95f6ffeddcad8812582fb2895c44263ce6ff
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest"
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:5055:5055/tcp
    tmpfs:
      - /tmp
    volumes:
      - overseerr:/config

  # https://docs.linuxserver.io/images/docker-sabnzbd
  sabnzbd:
    image: linuxserver/sabnzbd:4.0.3@sha256:2d8aa6864e31cae1b9a894156f9a6013a34d76a76ed137a9d85c3f9fa8282bb0
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest"
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:8080:8080/tcp
    tmpfs:
      - /tmp
    volumes:
      - sabnzbd:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-tautulli
  tautulli:
    image: linuxserver/tautulli:2.13.1@sha256:78ef0d6abf48b24a732624f6711117b6cbff7ddc022812c450f212c4e0bb67e8
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest"
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:8181:8181/tcp
    tmpfs:
      - /tmp
    volumes:
      - tautulli:/config

    # https://hub.docker.com/r/netdata/netdata
  netdata:
    image: netdata/netdata:v1.42.2@sha256:068dccfac13bee73296e5fb775dbe95b622ec9921d8b7e2d21aa1bb7801b9355
    privileged: true
    cap_add:
      - SYS_PTRACE
    environment:
      DOCKER_HOST: "/var/run/balena.sock"
      PGID: "990" # ls -nd /var/run/balena.sock | awk '{print $4}'
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.sysfs: 1
    ports:
      - 127.0.0.1:19999:19999/tcp
    security_opt:
      - apparmor:unconfined
    tmpfs:
      - /tmp
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata

  # https://docs.linuxserver.io/images/docker-duplicati
  duplicati:
    image: lscr.io/linuxserver/duplicati:v2.0.6.3-2.0.6.3_beta_2021-06-17-ls160@sha256:9cf7c7a14bf1474d44aa29d329552bf32af58090f4cfa5e61e35a88b2cd4677e
    restart: unless-stopped
    environment:
      PUID: "0"
      PGID: "0"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest"
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:8200:8200/tcp
    tmpfs:
      - /tmp
    volumes:
      - duplicati:/config
      # any volumes that might be worth backing up
      - syncthing:/volumes/syncthing
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - ombi:/volumes/ombi
      - overseerr:/volumes/overseerr
      - sabnzbd:/volumes/sabnzbd
      - tailscale:/volumes/tailscale
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - tautulli:/volumes/tautulli

  # https://docs.linuxserver.io/images/docker-syncthing
  syncthing:
    image: lscr.io/linuxserver/syncthing:1.24.0@sha256:970d5e9a95d130c6b4e235a7baee651a0d7d813566dcdd17bb88cff37a6258bf
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      DOCKER_MODS: "ghcr.io/klutchell/balena-mediaserver:latest"
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - 127.0.0.1:8384:8384/tcp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    tmpfs:
      - /tmp
    volumes:
      - syncthing:/config
      # any volumes that might be worth syncronizing between machines
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - ombi:/volumes/ombi
      - overseerr:/volumes/overseerr
      - sabnzbd:/volumes/sabnzbd
      - tailscale:/volumes/tailscale
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - tautulli:/volumes/tautulli

  # https://hub.docker.com/r/jc21/nginx-proxy-manager
  proxy:
    image: jc21/nginx-proxy-manager:2.10.4@sha256:e1000dd653d193ac70cb3635c27333b0183a11f987e2b1c6043589d9d948bc0f
    ports:
      - 80:80/tcp
      - 127.0.0.1:81:81/tcp
      - 443:443/tcp
    tmpfs:
      - /tmp
    volumes:
      - proxy:/data
      - letsencrypt:/etc/letsencrypt

  # https://hub.docker.com/r/tailscale/tailscale
  tailscale:
    image: tailscale/tailscale:v1.48.1@sha256:51c756718c30b15d1d3d228b1f4425cba646ec15da5d188a0d55c32b8ea4f378
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    labels:
      io.balena.features.kernel-modules: 1
    tmpfs:
      - /tmp
      - /var/run/
    volumes:
      - tailscale:/var/lib/tailscale
    environment:
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_SOCKET: "/var/run/tailscale/tailscaled.sock"
      TS_EXTRA_ARGS: "--reset --accept-routes"
      TS_AUTH_ONCE: "true"
      # TS_USERSPACE: "true"
      TS_HOSTNAME: mediaserver
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        # load the kernel module if it exists
        if modprobe wireguard 2>/dev/null
        then
          modinfo wireguard || true
          export TS_USERSPACE="${TS_USERSPACE:-false}"
        fi

        mkdir -p /dev/net
        [ ! -c /dev/net/tun ] && mknod /dev/net/tun c 10 200
        
        /usr/local/bin/containerboot &
        pid=$!

        sleep 5

        tailscale serve reset
        
        tailscale serve tls-terminated-tcp:8200 tcp://127.0.0.1:8200
        # tailscale serve tls-terminated-tcp:8096 tcp://127.0.0.1:8096
        tailscale serve tls-terminated-tcp:19999 tcp://127.0.0.1:19999
        tailscale serve tls-terminated-tcp:6789 tcp://127.0.0.1:6789
        tailscale serve tls-terminated-tcp:5076 tcp://127.0.0.1:5076
        tailscale serve tls-terminated-tcp:3579 tcp://127.0.0.1:3579
        tailscale serve tls-terminated-tcp:5055 tcp://127.0.0.1:5055
        # tailscale serve tls-terminated-tcp:32400 tcp://127.0.0.1:32400
        tailscale serve tls-terminated-tcp:9696 tcp://127.0.0.1:9696
        tailscale serve tls-terminated-tcp:81 tcp://127.0.0.1:81
        tailscale serve tls-terminated-tcp:7878 tcp://127.0.0.1:7878
        tailscale serve tls-terminated-tcp:8989 tcp://127.0.0.1:8989
        tailscale serve tls-terminated-tcp:8080 tcp://127.0.0.1:8080
        tailscale serve tls-terminated-tcp:8181 tcp://127.0.0.1:8181
        tailscale serve tls-terminated-tcp:8384 tcp://127.0.0.1:8384

        tailscale serve status

        wait $pid
