version: "2.1"

volumes:
  downloads: {}
  duplicati: {}
  jellyfin: {}
  letsencrypt: {}
  netdatalib: {}
  netdatacache: {}
  nzbhydra: {}
  ombi: {}
  overseerr: {}
  plex: {}
  prowlarr: {}
  proxy: {}
  radarr: {}
  sabnzbd: {}
  sonarr: {}
  syncthing: {}
  tautulli: {}

services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    build:
      context: docker-mod
      dockerfile: Dockerfile.plex
    restart: "on-failure"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    labels:
      io.balena.features.kernel-modules: 1
    devices:
      - /dev/dri:/dev/dri
    environment:
      PUID: "1000"
      PGID: "1000"
      TAILSCALE_STATE_DIR: /tmp/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: plex
      TAILSCALE_SERVE_PORT: 32400
    ports:
      - 127.0.0.1:32400:32400/tcp
    tmpfs:
      - /tmp
    volumes:
      - plex:/config
      - downloads:/downloads
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        [[ ${DISABLE,,} =~ true|yes|on|1 ]] && exit 0
        exec /init

  # https://docs.linuxserver.io/images/docker-jellyfin
  jellyfin:
    build:
      context: docker-mod
      dockerfile: Dockerfile.jellyfin
    restart: "on-failure"
    devices:
      - /dev/dri:/dev/dri
    environment:
      PUID: "1000"
      PGID: "1000"
      TAILSCALE_STATE_DIR: /tmp/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: jellyfin
      TAILSCALE_SERVE_PORT: 8096
    ports:
      - 127.0.0.1:8096:8096/tcp
    tmpfs:
      - /tmp
    volumes:
      - jellyfin:/config
      - downloads:/downloads
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        [[ ${DISABLE,,} =~ true|yes|on|1 ]] && exit 0
        exec /init

  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    build:
      context: docker-mod
      dockerfile: Dockerfile.sonarr
    restart: "on-failure"
    environment:
      PUID: "1000"
      PGID: "1000"
      TAILSCALE_STATE_DIR: /tmp/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: sonarr
      TAILSCALE_SERVE_PORT: 8989
    ports:
      - 127.0.0.1:8989:8989/tcp
    tmpfs:
      - /tmp
    volumes:
      - sonarr:/config
      - downloads:/downloads
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        [[ ${DISABLE,,} =~ true|yes|on|1 ]] && exit 0
        exec /init

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    build:
      context: docker-mod
      dockerfile: Dockerfile.radarr
    restart: "on-failure"
    environment:
      PUID: "1000"
      PGID: "1000"
      TAILSCALE_STATE_DIR: /tmp/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: radarr
      TAILSCALE_SERVE_PORT: 7878
    ports:
      - 127.0.0.1:7878:7878/tcp
    tmpfs:
      - /tmp
    volumes:
      - radarr:/config
      - downloads:/downloads
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        [[ ${DISABLE,,} =~ true|yes|on|1 ]] && exit 0
        exec /init

  # https://docs.linuxserver.io/images/docker-prowlarr
  prowlarr:
    build:
      context: docker-mod
      dockerfile: Dockerfile.prowlarr
    restart: "on-failure"
    environment:
      PUID: "1000"
      PGID: "1000"
      TAILSCALE_STATE_DIR: /tmp/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: prowlarr
      TAILSCALE_SERVE_PORT: 9696
    ports:
      - 127.0.0.1:9696:9696/tcp
    tmpfs:
      - /tmp
    volumes:
      - prowlarr:/config
      - downloads:/downloads
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        [[ ${DISABLE,,} =~ true|yes|on|1 ]] && exit 0
        exec /init

  # https://docs.linuxserver.io/images/docker-nzbhydra
  nzbhydra:
    build:
      context: docker-mod
      dockerfile: Dockerfile.nzbhydra
    restart: "on-failure"
    environment:
      PUID: "1000"
      PGID: "1000"
      TAILSCALE_STATE_DIR: /tmp/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: nzbhydra
      TAILSCALE_SERVE_PORT: 5076
    ports:
      - 127.0.0.1:5076:5076/tcp
    tmpfs:
      - /tmp
    volumes:
      - nzbhydra:/config
      - downloads:/downloads
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        [[ ${DISABLE,,} =~ true|yes|on|1 ]] && exit 0
        exec /init

  # https://docs.linuxserver.io/images/docker-ombi
  ombi:
    build:
      context: docker-mod
      dockerfile: Dockerfile.ombi
    restart: "on-failure"
    environment:
      PUID: "1000"
      PGID: "1000"
      TAILSCALE_STATE_DIR: /tmp/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: ombi
      TAILSCALE_SERVE_PORT: 3579
    ports:
      - 127.0.0.1:3579:3579/tcp
    tmpfs:
      - /tmp
    volumes:
      - ombi:/config
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        [[ ${DISABLE,,} =~ true|yes|on|1 ]] && exit 0
        exec /init

  # https://docs.linuxserver.io/images/docker-overseerr
  overseerr:
    build:
      context: docker-mod
      dockerfile: Dockerfile.overseerr
    restart: "on-failure"
    environment:
      PUID: "1000"
      PGID: "1000"
      TAILSCALE_STATE_DIR: /tmp/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: overseerr
      TAILSCALE_SERVE_PORT: 5055
    ports:
      - 127.0.0.1:5055:5055/tcp
    tmpfs:
      - /tmp
    volumes:
      - overseerr:/config
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        [[ ${DISABLE,,} =~ true|yes|on|1 ]] && exit 0
        exec /init

  # https://docs.linuxserver.io/images/docker-sabnzbd
  sabnzbd:
    build:
      context: docker-mod
      dockerfile: Dockerfile.sabnzbd
    restart: "on-failure"
    environment:
      PUID: "1000"
      PGID: "1000"
      TAILSCALE_STATE_DIR: /tmp/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: sabnzbd
      TAILSCALE_SERVE_PORT: 8080
    ports:
      - 127.0.0.1:8080:8080/tcp
    tmpfs:
      - /tmp
    volumes:
      - sabnzbd:/config
      - downloads:/downloads
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        [[ ${DISABLE,,} =~ true|yes|on|1 ]] && exit 0
        exec /init

  # https://docs.linuxserver.io/images/docker-tautulli
  tautulli:
    build:
      context: docker-mod
      dockerfile: Dockerfile.tautulli
    restart: "on-failure"
    environment:
      PUID: "1000"
      PGID: "1000"
      TAILSCALE_STATE_DIR: /tmp/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: tautulli
      TAILSCALE_SERVE_PORT: 8181
    ports:
      - 127.0.0.1:8181:8181/tcp
    tmpfs:
      - /tmp
    volumes:
      - tautulli:/config
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        [[ ${DISABLE,,} =~ true|yes|on|1 ]] && exit 0
        exec /init

  # https://hub.docker.com/r/netdata/netdata
  netdata:
    image: netdata/netdata:v1.43.2@sha256:0116a5a4dbfedd84d80eba320f5d99d547da5d9bc0841adde0d7f13bed25f73a
    restart: "on-failure"
    privileged: true
    cap_add:
      - SYS_PTRACE
    environment:
      DOCKER_HOST: "/var/run/balena.sock"
      PGID: "990" # ls -nd /var/run/balena.sock | awk '{print $4}'
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.sysfs: 1
    ports:
      - 127.0.0.1:19999:19999/tcp
    security_opt:
      - apparmor:unconfined
    tmpfs:
      - /tmp
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        [[ ${DISABLE,,} =~ true|yes|on|1 ]] && exit 0
        exec /usr/sbin/run.sh

  # https://docs.linuxserver.io/images/docker-duplicati
  duplicati:
    build:
      context: docker-mod
      dockerfile: Dockerfile.duplicati
    restart: "on-failure"
    environment:
      PUID: "0"
      PGID: "0"
      TAILSCALE_STATE_DIR: /tmp/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: duplicati
      TAILSCALE_SERVE_PORT: 8200
    ports:
      - 127.0.0.1:8200:8200/tcp
    tmpfs:
      - /tmp
    volumes:
      - duplicati:/config
      # any volumes that might be worth backing up
      - syncthing:/volumes/syncthing
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - ombi:/volumes/ombi
      - overseerr:/volumes/overseerr
      - sabnzbd:/volumes/sabnzbd
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - tautulli:/volumes/tautulli
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        [[ ${DISABLE,,} =~ true|yes|on|1 ]] && exit 0
        exec /init

  # https://docs.linuxserver.io/images/docker-syncthing
  syncthing:
    build:
      context: docker-mod
      dockerfile: Dockerfile.duplicati
    restart: "on-failure"
    environment:
      PUID: "1000"
      PGID: "1000"
      TAILSCALE_STATE_DIR: /tmp/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: syncthing
      TAILSCALE_SERVE_PORT: 8384
    ports:
      - 127.0.0.1:8384:8384/tcp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    tmpfs:
      - /tmp
    volumes:
      - syncthing:/config
      # any volumes that might be worth syncronizing between machines
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - ombi:/volumes/ombi
      - overseerr:/volumes/overseerr
      - sabnzbd:/volumes/sabnzbd
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - tautulli:/volumes/tautulli
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        [[ ${DISABLE,,} =~ true|yes|on|1 ]] && exit 0
        exec /init

  # https://hub.docker.com/r/jc21/nginx-proxy-manager
  # https://github.com/NginxProxyManager/nginx-proxy-manager
  # https://nginxproxymanager.com/
  nginx-proxy-manager:
    build:
      context: docker-mod
      dockerfile: Dockerfile.nginx-proxy-manager
    restart: "on-failure"
    environment:
      TAILSCALE_STATE_DIR: /tmp/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_USE_SSH: 1
      TAILSCALE_HOSTNAME: nginx
      TAILSCALE_SERVE_PORT: 81
    ports:
      - 80:80/tcp
      - 127.0.0.1:81:81/tcp
      - 443:443/tcp
    tmpfs:
      - /tmp
    volumes:
      - proxy:/data
      - letsencrypt:/etc/letsencrypt
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        [[ ${DISABLE,,} =~ true|yes|on|1 ]] && exit 0
        exec /init
