version: "2.1"

volumes:
  downloads: {}
  duplicati: {}
  jellyfin: {}
  letsencrypt: {}
  netdatalib: {}
  netdatacache: {}
  nzbget: {}
  nzbhydra: {}
  ombi: {}
  overseerr: {}
  plex: {}
  prowlarr: {}
  proxy: {}
  radarr: {}
  sabnzbd: {}
  sonarr: {}
  syncthing: {}
  tailscale: {}
  tautulli: {}

services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    image: linuxserver/plex:1.32.5@sha256:4f79fb474e01c629301c90bd3f39d47cc83678e6aceda15effa3e6320f8e296b
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    devices:
      - /dev/dri:/dev/dri
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 32400:32400/tcp
    tmpfs:
      - /tmp
    volumes:
      - plex:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-jellyfin
  jellyfin:
    image: linuxserver/jellyfin:10.8.10@sha256:256102cfaa0995cca107e472f0bb45c9430b27dee3eec5406575b134f0c04c13
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    devices:
      - /dev/dri:/dev/dri
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    tmpfs:
      - /tmp
    volumes:
      - jellyfin:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-nzbget
  nzbget:
    image: linuxserver/nzbget:21.1.20230119@sha256:ed58a6471591126adee01e704d35264979640bede1fca7ffa13a21d6643c5a18
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:6789:6789/tcp
    tmpfs:
      - /tmp
    volumes:
      - nzbget:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:3.0.10@sha256:3776ba2231121dda29198f219f4de2cc6a19b80261915dbf538d426283d620cc
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    depends_on:
      - nzbhydra
      - nzbget
      - prowlarr
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:8989:8989/tcp
    tmpfs:
      - /tmp
    volumes:
      - sonarr:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    image: linuxserver/radarr:4.7.5@sha256:64e6ecdc613c0c91bcae67cad88ce6555a33cb6f71c9214209095b76de07cfb7
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    depends_on:
      - nzbhydra
      - nzbget
      - prowlarr
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:7878:7878/tcp
    tmpfs:
      - /tmp
    volumes:
      - radarr:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-prowlarr
  prowlarr:
    image: linuxserver/prowlarr:1.8.2-develop@sha256:f232ad096651bfde350f90e97d7f79840b0bcb9294758316432623262e77e544
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:9696:9696/tcp
    tmpfs:
      - /tmp
    volumes:
      - prowlarr:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-nzbhydra
  nzbhydra:
    image: linuxserver/nzbhydra2:5.1.10@sha256:689a53faa6e3c3f6684133893d74622dabfc43a3523ee466db89ba388d15cdfd
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:5076:5076/tcp
    tmpfs:
      - /tmp
    volumes:
      - nzbhydra:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-ombi
  ombi:
    image: linuxserver/ombi:4.39.1@sha256:a830cb7f92c92b869a8202df7b1b6b0c15c796abac8ecc53ba6660d72e2485d1
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:3579:3579/tcp
    tmpfs:
      - /tmp
    volumes:
      - ombi:/config

  # https://docs.linuxserver.io/images/docker-overseerr
  overseerr:
    image: lscr.io/linuxserver/overseerr:1.33.2@sha256:7a9c8e6a4ac9edfe6f1ef786e013efb5f5cf5a1095b9a94fb354765eca7ecef6
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:5055:5055/tcp
    tmpfs:
      - /tmp
    volumes:
      - overseerr:/config

  # https://docs.linuxserver.io/images/docker-sabnzbd
  sabnzbd:
    image: linuxserver/sabnzbd:4.0.3@sha256:8a719b74a114e7fd08f2f2e8f2ac8287029bf35d60ca8f035ed12bb798aed828
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:8080:8080/tcp
    tmpfs:
      - /tmp
    volumes:
      - sabnzbd:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-tautulli
  tautulli:
    image: linuxserver/tautulli:2.12.5@sha256:4bf16db026fd0aa81f4afa02cb92827f1e072b7de5a7cb71e767e960f8620f1a
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:8181:8181/tcp
    tmpfs:
      - /tmp
    volumes:
      - tautulli:/config

    # https://hub.docker.com/r/netdata/netdata
  netdata:
    image: netdata/netdata:v1.42.1@sha256:c1943ce672822b07103ea4b17050d60167f31f3e409eb2fe02a1241f0352c060
    privileged: true
    cap_add:
      - SYS_PTRACE
    environment:
      DOCKER_HOST: "/var/run/balena.sock"
      PGID: "990" # ls -nd /var/run/balena.sock | awk '{print $4}'
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.sysfs: 1
    ports:
      - 127.0.0.1:19999:19999/tcp
    security_opt:
      - apparmor:unconfined
    tmpfs:
      - /tmp
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata

  # https://docs.linuxserver.io/images/docker-duplicati
  duplicati:
    image: lscr.io/linuxserver/duplicati:v2.0.6.3-2.0.6.3_beta_2021-06-17-ls160@sha256:9cf7c7a14bf1474d44aa29d329552bf32af58090f4cfa5e61e35a88b2cd4677e
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "0"
      PGID: "0"
    ports:
      - 127.0.0.1:8200:8200/tcp
    tmpfs:
      - /tmp
    volumes:
      - duplicati:/config
      # any volumes that might be worth backing up
      - syncthing:/volumes/syncthing
      - plex:/volumes/plex
      - nzbget:/volumes/nzbget
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - ombi:/volumes/ombi
      - overseerr:/volumes/overseerr
      - sabnzbd:/volumes/sabnzbd
      - tailscale:/volumes/tailscale
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - tautulli:/volumes/tautulli

  # https://docs.linuxserver.io/images/docker-syncthing
  syncthing:
    image: lscr.io/linuxserver/syncthing:1.23.7@sha256:c1ee17d0f7e1f3aec022312e8bf984c8089d0fff622a3fad8c6079abf0283710
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:8384:8384/tcp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    tmpfs:
      - /tmp
    volumes:
      - syncthing:/config
      # any volumes that might be worth syncronizing between machines
      - plex:/volumes/plex
      - nzbget:/volumes/nzbget
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - ombi:/volumes/ombi
      - overseerr:/volumes/overseerr
      - sabnzbd:/volumes/sabnzbd
      - tailscale:/volumes/tailscale
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - tautulli:/volumes/tautulli

  # https://hub.docker.com/r/jc21/nginx-proxy-manager
  proxy:
    image: jc21/nginx-proxy-manager:2.10.4@sha256:e1000dd653d193ac70cb3635c27333b0183a11f987e2b1c6043589d9d948bc0f
    ports:
      - 80:80/tcp
      - 127.0.0.1:81:81/tcp
      - 443:443/tcp
    tmpfs:
      - /tmp
    volumes:
      - proxy:/data
      - letsencrypt:/etc/letsencrypt

  # https://hub.docker.com/r/tailscale/tailscale
  tailscale:
    image: tailscale/tailscale:v1.46.1@sha256:8abcbcfe179c454ab4c3b583626c4e5b2edcb7c0851fe09ba3313d4ca02aacdc
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    labels:
      - io.balena.features.kernel-modules=1
    tmpfs:
      - /tmp
      - /var/run/
    volumes:
      - tailscale:/var/lib/tailscale
    environment:
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_SOCKET: "/var/run/tailscale/tailscaled.sock"
      TS_EXTRA_ARGS: "--reset --accept-routes"
      TS_AUTH_ONCE: "true"
      # TS_USERSPACE: "true"
      # TS_ROUTES: 172.18.0.0/16
      TS_HOSTNAME: mediaserver
      # TS_DEST_IP: 127.0.0.1
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        # load the kernel module if it exists
        if modprobe wireguard 2>/dev/null
        then
          modinfo wireguard || true
          export TS_USERSPACE="${TS_USERSPACE:-false}"
        fi

        mkdir -p /dev/net
        [ ! -c /dev/net/tun ] && mknod /dev/net/tun c 10 200
        
        /usr/local/bin/containerboot &
        pid=$!

        sleep 5

        tailscale serve reset
        
        tailscale serve tls-terminated-tcp:8200 tcp://127.0.0.1:8200
        # tailscale serve tls-terminated-tcp:8096 tcp://127.0.0.1:8096
        tailscale serve tls-terminated-tcp:19999 tcp://127.0.0.1:19999
        tailscale serve tls-terminated-tcp:6789 tcp://127.0.0.1:6789
        tailscale serve tls-terminated-tcp:5076 tcp://127.0.0.1:5076
        tailscale serve tls-terminated-tcp:3579 tcp://127.0.0.1:3579
        tailscale serve tls-terminated-tcp:5055 tcp://127.0.0.1:5055
        # tailscale serve tls-terminated-tcp:32400 tcp://127.0.0.1:32400
        tailscale serve tls-terminated-tcp:9696 tcp://127.0.0.1:9696
        tailscale serve tls-terminated-tcp:81 tcp://127.0.0.1:81
        tailscale serve tls-terminated-tcp:7878 tcp://127.0.0.1:7878
        tailscale serve tls-terminated-tcp:8989 tcp://127.0.0.1:8989
        tailscale serve tls-terminated-tcp:8080 tcp://127.0.0.1:8080
        tailscale serve tls-terminated-tcp:8181 tcp://127.0.0.1:8181
        tailscale serve tls-terminated-tcp:8384 tcp://127.0.0.1:8384

        tailscale serve status

        wait $pid
