version: "2.1"

volumes:
  plex: {}
  nzbget: {}
  sonarr: {}
  radarr: {}
  nzbhydra: {}
  duplicati: {}
  jellyfin: {}
  prowlarr: {}
  ombi: {}
  overseerr: {}
  tailscale: {}
  syncthing: {}
  netdatalib: {}
  netdatacache: {}
  downloads: {}
  proxy: {}
  letsencrypt: {}

services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    image: linuxserver/plex:1.32.5@sha256:59f2095f1bc4ebd4bc5bf07c28ef55082039d42dd5f34806901c24efa893ee1b
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    devices:
      - /dev/dri:/dev/dri
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 32400:32400/tcp
    tmpfs:
      - /tmp
    volumes:
      - plex:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-jellyfin
  jellyfin:
    image: linuxserver/jellyfin:10.8.10@sha256:167fb73634860ef5506b1760838dcdb2870fdb24e3a27b5b53104c54a14e5991
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    devices:
      - /dev/dri:/dev/dri
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    tmpfs:
      - /tmp
    volumes:
      - jellyfin:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-nzbget
  nzbget:
    image: linuxserver/nzbget:21.1.20230119@sha256:ed58a6471591126adee01e704d35264979640bede1fca7ffa13a21d6643c5a18
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:6789:6789/tcp
    tmpfs:
      - /tmp
    volumes:
      - nzbget:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:3.0.10@sha256:cdddb991ebdc97a6f6344fc46de8249c03a22f3f0ab17fcac652df20b587d1ee
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    depends_on:
      - nzbhydra
      - nzbget
      - prowlarr
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:8989:8989/tcp
    tmpfs:
      - /tmp
    volumes:
      - sonarr:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    image: linuxserver/radarr:4.6.4@sha256:c96d598ad21f5f1c2fb7b4718261af2899cb48206317402145cce4281d607830
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    depends_on:
      - nzbhydra
      - nzbget
      - prowlarr
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:7878:7878/tcp
    tmpfs:
      - /tmp
    volumes:
      - radarr:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-prowlarr
  prowlarr:
    image: linuxserver/prowlarr:1.7.2-develop@sha256:e43f4564347ab7e89b6890645a9497919e8771062bf9b70ae4fe34904fabf36b
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:9696:9696/tcp
    tmpfs:
      - /tmp
    volumes:
      - prowlarr:/config

  # https://docs.linuxserver.io/images/docker-nzbhydra
  nzbhydra:
    image: linuxserver/nzbhydra2:5.1.9@sha256:eb53b8c410157f78745b609fc94b0e4b71c9195a529418e6474a4009418d8758
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:5076:5076/tcp
    tmpfs:
      - /tmp
    volumes:
      - nzbhydra:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-ombi
  ombi:
    image: linuxserver/ombi:4.39.1@sha256:691e110450cec250bc7ace3b8075b81221b2668722745abd339498b8a45cb6fe
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:3579:3579/tcp
    tmpfs:
      - /tmp
    volumes:
      - ombi:/config

  # https://docs.linuxserver.io/images/docker-overseerr
  overseerr:
    image: lscr.io/linuxserver/overseerr:1.33.0@sha256:607543d41495edc84727cdabce19efce334afde488b0618ae94ff6ecd7e3b880
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:5055:5055/tcp
    tmpfs:
      - /tmp
    volumes:
      - overseerr:/config

  # https://github.com/klutchell/balena-tailscale
  tailscale:
    image: bh.cr/klutchell_blocks/tailscale-amd64/1.44.0
    network_mode: host
    restart: on-failure
    cap_add:
      - net_admin
      - net_raw
      - sys_module
    labels:
      - io.balena.features.kernel-modules=1
    tmpfs:
      - /tmp
      - /var/run/
    volumes:
      - tailscale:/var/lib/tailscale

    # https://hub.docker.com/r/netdata/netdata
  netdata:
    image: netdata/netdata:v1.41.0@sha256:2801d57b2050bc9071be8279d6f70a3ffe71a7881c84b524104080375ae0cb46
    privileged: true
    cap_add:
      - SYS_PTRACE
    environment:
      DOCKER_HOST: "/var/run/balena.sock"
      PGID: "990" # ls -nd /var/run/balena.sock | awk '{print $4}'
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.sysfs: 1
    ports:
      - 127.0.0.1:19999:19999/tcp
    security_opt:
      - apparmor:unconfined
    tmpfs:
      - /tmp
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata

  # https://docs.linuxserver.io/images/docker-duplicati
  duplicati:
    image: lscr.io/linuxserver/duplicati:v2.0.6.3-2.0.6.3_beta_2021-06-17-ls160@sha256:9cf7c7a14bf1474d44aa29d329552bf32af58090f4cfa5e61e35a88b2cd4677e
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "0"
      PGID: "0"
    ports:
      - 127.0.0.1:8200:8200/tcp
    tmpfs:
      - /tmp
    volumes:
      - duplicati:/config
      # any volumes that might be worth backing up
      - syncthing:/volumes/syncthing
      - plex:/volumes/plex
      - nzbget:/volumes/nzbget
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr∂
      - ombi:/volumes/ombi
      - overseerr:/volumes/overseerr
      - tailscale:/volumes/tailscale
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy

  # https://docs.linuxserver.io/images/docker-syncthing
  syncthing:
    image: lscr.io/linuxserver/syncthing:1.23.6@sha256:4437694f86cef4dce5e78a1c2f609b9fbca8d6b19e1e69b93a17a238d7406fa7
    entrypoint: /bin/sh -c "[ -n \"${DISABLE}\" ] || exec /init"
    restart: on-failure
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - 127.0.0.1:8384:8384/tcp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    tmpfs:
      - /tmp
    volumes:
      - syncthing:/config
      # any volumes that might be worth syncronizing between machines
      - plex:/volumes/plex
      - nzbget:/volumes/nzbget
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - ombi:/volumes/ombi
      - overseerr:/volumes/overseerr
      - tailscale:/volumes/tailscale
      - downloads:/volumes/downloads

  # https://hub.docker.com/r/jc21/nginx-proxy-manager
  proxy:
    image: jc21/nginx-proxy-manager:2.10.3@sha256:e5407dfe0577301171f403ec6b8a01b87eca5420416a907f9c42775428e22fee
    ports:
      - 80:80/tcp
      - 127.0.0.1:81:81/tcp
      - 443:443/tcp
    tmpfs:
      - /tmp
    volumes:
      - proxy:/data
      - letsencrypt:/etc/letsencrypt
