version: "2.1"

x-s6-service: &s6-service
  restart: "on-failure"
  tmpfs:
    - /tmp
  environment: &s6-environment
    S6_VERBOSITY: 2
  entrypoint:
    - /bin/bash
    - -c
  command:
    - |
      [[ ${DISABLE,,} =~ true|yes|on|1 ]] && exit 0
      exec /init

x-linuxserver-service: &linuxserver-service
  <<: *s6-service
  environment: &linuxserver-environment
    <<: *s6-environment
    PUID: "1000"
    PGID: "1000"

volumes:
  downloads: {}
  duplicati: {}
  jellyfin: {}
  letsencrypt: {}
  netdatalib: {}
  netdatacache: {}
  nzbhydra: {}
  ombi: {}
  overseerr: {}
  plex: {}
  prowlarr: {}
  proxy: {}
  radarr: {}
  sabnzbd: {}
  sonarr: {}
  syncthing: {}
  tautulli: {}
  tailscale: {}

services:
  # https://docs.linuxserver.io/images/docker-duplicati
  duplicati:
    <<: *linuxserver-service
    image: lscr.io/linuxserver/duplicati:2.0.7@sha256:9a1c4a1e3636459cff7ff25388b24a1219d0c02cc6012243cc6fe33ba8e3d514
    environment:
      <<: *linuxserver-environment
      PUID: "0"
      PGID: "0"
    ports:
      - 127.0.0.1:8200:8200/tcp
    volumes:
      - duplicati:/config
      # any volumes that might be worth backing up
      - syncthing:/volumes/syncthing
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - ombi:/volumes/ombi
      - overseerr:/volumes/overseerr
      - sabnzbd:/volumes/sabnzbd
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - tautulli:/volumes/tautulli

  # https://docs.linuxserver.io/images/docker-jellyfin
  jellyfin:
    <<: *linuxserver-service
    image: lscr.io/linuxserver/jellyfin:10.8.13@sha256:b46667ef4813fe0bfc33b1dd2428991857aca09aae105f1bf9c724982a7865cf
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 127.0.0.1:8096:8096/tcp
    volumes:
      - jellyfin:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-nzbhydra
  nzbhydra:
    <<: *linuxserver-service
    image: lscr.io/linuxserver/nzbhydra2:5.3.7@sha256:7dc68929450f8743f30e09f1d123c016a982d06ac71004ace82f7f188c634586
    ports:
      - 127.0.0.1:5076:5076/tcp
    volumes:
      - nzbhydra:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-ombi
  ombi:
    <<: *linuxserver-service
    image: lscr.io/linuxserver/ombi:4.43.5@sha256:a4f9fba25f2cbf4137bb6b811a91656cec483011ac80554cd540152d042cee39
    ports:
      - 127.0.0.1:3579:3579/tcp
    volumes:
      - ombi:/config

  # https://docs.linuxserver.io/images/docker-overseerr
  overseerr:
    <<: *linuxserver-service
    image: lscr.io/linuxserver/overseerr:1.33.2@sha256:0d704a11a0c7f56a6091031b11413a6e017242ba18f787bf2a03f3979a18c95d
    ports:
      - 127.0.0.1:5055:5055/tcp
    volumes:
      - overseerr:/config

  # https://docs.linuxserver.io/images/docker-plex
  plex:
    <<: *linuxserver-service
    image: lscr.io/linuxserver/plex:1.32.8@sha256:9f87f22e66be3cb980f0c69c6e41179c694f856a8e9262f21eb060e97fd21601
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 127.0.0.1:32400:32400/tcp
    volumes:
      - plex:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-prowlarr
  prowlarr:
    <<: *linuxserver-service
    image: lscr.io/linuxserver/prowlarr:1.12.2-develop@sha256:85bf1cb7adcea986e9dadc63ad70eb15d59e0a1858cf1d3398864c00f687d7b8
    ports:
      - 127.0.0.1:9696:9696/tcp
    volumes:
      - prowlarr:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    <<: *linuxserver-service
    image: lscr.io/linuxserver/radarr:5.2.6@sha256:5065337112be3d83df0130a401f5789c46f575e7439b2d4151c97b8921de0456
    ports:
      - 127.0.0.1:7878:7878/tcp
    volumes:
      - radarr:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-sabnzbd
  sabnzbd:
    <<: *linuxserver-service
    image: lscr.io/linuxserver/sabnzbd:4.2.1@sha256:a633d0d2b10775955d28445f08bc878de36e9466158150b3721a792af542e786
    ports:
      - 127.0.0.1:8080:8080/tcp
    volumes:
      - sabnzbd:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    <<: *linuxserver-service
    image: lscr.io/linuxserver/sonarr:4.0.1@sha256:6658221d9ccc80b93f0a15a695f064ee6ee520c6eb16afdeff03fcddc1181eef
    ports:
      - 127.0.0.1:8989:8989/tcp
    volumes:
      - sonarr:/config
      - downloads:/downloads

  # https://docs.linuxserver.io/images/docker-syncthing
  syncthing:
    <<: *linuxserver-service
    image: lscr.io/linuxserver/syncthing:1.27.2@sha256:4416a1d740bc8721de795757a715b3b2887f6f3b0202dd41c3e602d7acb63acc
    ports:
      - 127.0.0.1:8384:8384/tcp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - syncthing:/config
      # any volumes that might be worth syncronizing between machines
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - ombi:/volumes/ombi
      - overseerr:/volumes/overseerr
      - sabnzbd:/volumes/sabnzbd
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - tautulli:/volumes/tautulli

  # https://docs.linuxserver.io/images/docker-tautulli
  tautulli:
    <<: *linuxserver-service
    image: lscr.io/linuxserver/tautulli:2.13.4@sha256:b265e48914776e8675f361b9ba771d33485e360ab20f63a3b86c1d7999a91362
    ports:
      - 127.0.0.1:8181:8181/tcp
    volumes:
      - tautulli:/config

  # https://hub.docker.com/r/jc21/nginx-proxy-manager
  # https://github.com/NginxProxyManager/nginx-proxy-manager
  # https://nginxproxymanager.com/
  nginx-proxy-manager:
    <<: *s6-service
    image: jc21/nginx-proxy-manager:2.11.1@sha256:5b2d87d3c060e4a364df0109d8188d816ec07273697ad350aa4beeab63529f74
    ports:
      - 80:80/tcp
      - 127.0.0.1:81:81/tcp
      - 443:443/tcp
    volumes:
      - proxy:/data
      - letsencrypt:/etc/letsencrypt

  # https://hub.docker.com/r/netdata/netdata
  netdata:
    image: netdata/netdata:v1.44.1@sha256:4363d046c878507036b977e9716828bffc26913b1b3f977e83015d370ffc154a
    restart: "on-failure"
    privileged: true
    cap_add:
      - SYS_PTRACE
    environment:
      DOCKER_HOST: "/var/run/balena.sock"
      PGID: "990" # ls -nd /var/run/balena.sock | awk '{print $4}'
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.sysfs: 1
    ports:
      - 127.0.0.1:19999:19999/tcp
    security_opt:
      - apparmor:unconfined
    tmpfs:
      - /tmp
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata

  # https://hub.docker.com/r/tailscale/tailscale
  # https://github.com/tailscale/tailscale/blob/main/cmd/containerboot/main.go
  # https://tailscale.com/kb/1282/docker
  # https://tailscale.com/kb/1278/tailscaled
  # https://tailscale.com/kb/1241/tailscale-up
  # https://tailscale.com/kb/1242/tailscale-serve
  # https://tailscale.com/kb/1311/tailscale-funnel
  tailscale:
    build: tailscale
    restart: "on-failure"
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false
      TS_AUTH_ONCE: false
      TS_HOSTNAME: mediaserver
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    labels:
      io.balena.features.kernel-modules: 1
    tmpfs:
      - /tmp
      - /run
    volumes:
      - tailscale:/var/lib/tailscale
